import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/myui/Navbar"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

          {/* Fixed Navbar to Ensure Accessibility */}
          <div className="fixed top-0 left-0 w-full bg-white dark:bg-gray-900 shadow-md z-[100]">
            <Navbar />
          </div>

          {/* Push content down so it's not covered by the fixed navbar */}
          <div className="pt-16">{children}</div>
       
      </body>
    </html>
  );
}
